-- Concert ticketing schema.
-- One statement per semicolon. No PL/SQL blocks: the migration runner
-- splits on ';' and a block would be split in the middle.

CREATE TABLE venue (
  venue_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     VARCHAR2(200) NOT NULL,
  city     VARCHAR2(100) NOT NULL
);

CREATE TABLE seat (
  seat_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id    NUMBER(10) NOT NULL REFERENCES venue(venue_id),
  section     VARCHAR2(20) NOT NULL,
  row_label   VARCHAR2(10) NOT NULL,
  seat_number NUMBER(4) NOT NULL,
  CONSTRAINT uq_seat_position UNIQUE (venue_id, section, row_label, seat_number)
);

CREATE TABLE show_event (
  show_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id  NUMBER(10) NOT NULL REFERENCES venue(venue_id),
  title     VARCHAR2(200) NOT NULL,
  artist    VARCHAR2(200) NOT NULL,
  starts_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE seat_hold (
  hold_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_id    NUMBER(10) NOT NULL REFERENCES show_event(show_id),
  email      VARCHAR2(320) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  status     VARCHAR2(10) NOT NULL,
  CONSTRAINT ck_hold_status CHECK (status IN ('ACTIVE','CONFIRMED','RELEASED','EXPIRED'))
);

CREATE TABLE show_seat (
  show_seat_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  show_id      NUMBER(10) NOT NULL REFERENCES show_event(show_id),
  seat_id      NUMBER(10) NOT NULL REFERENCES seat(seat_id),
  status       VARCHAR2(10) NOT NULL,
  price_cents  NUMBER(10) NOT NULL,
  hold_id      NUMBER(10) REFERENCES seat_hold(hold_id),
  expires_at   TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uq_show_seat UNIQUE (show_id, seat_id),
  CONSTRAINT ck_show_seat_status CHECK (status IN ('AVAILABLE','HELD','SOLD')),
  CONSTRAINT ck_held_consistency CHECK (
    (status = 'HELD' AND hold_id IS NOT NULL AND expires_at IS NOT NULL)
    OR (status <> 'HELD' AND hold_id IS NULL AND expires_at IS NULL)
  )
);

CREATE TABLE customer_order (
  order_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hold_id     NUMBER(10) NOT NULL UNIQUE REFERENCES seat_hold(hold_id),
  email       VARCHAR2(320) NOT NULL,
  total_cents NUMBER(10) NOT NULL,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE ticket (
  ticket_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     NUMBER(10) NOT NULL REFERENCES customer_order(order_id),
  show_seat_id NUMBER(10) NOT NULL REFERENCES show_seat(show_seat_id),
  price_cents  NUMBER(10) NOT NULL,
  CONSTRAINT uq_ticket_show_seat UNIQUE (show_seat_id)
);

CREATE INDEX ix_show_seat_show_status ON show_seat (show_id, status);

CREATE INDEX ix_show_seat_expiry ON show_seat (status, expires_at);
